export const bookName = [
  { name: "Select your car type", value: "" },
  {
    name: "Audi A1 S-Line",
    value: "Audi A1 S-Line",
    img: "/images/audis1.jpg",
    id: crypto.randomUUID(),
  },
  {
    name: "VW Golf 6",
    value: "VW Golf 6",
    img: "/images/vw-golf.jpg",
    id: crypto.randomUUID(),
  },
  {
    name: "Toyota Camry",
    value: "Toyota Camry",
    img: "/images/toyota.jpg",
    id: crypto.randomUUID(),
  },
  {
    name: "BMW 320 Modernline",
    value: "BMW 320 Modernline",
    img: "/images/bmw.jpg",
    id: crypto.randomUUID(),
  },
  {
    name: "Mercedeces-Benz GKL",
    value: "Mercedeces-Benz GKL",
    img: "/images/mercedes.jpg",
    id: crypto.randomUUID(),
  },
  {
    name: "VW Passat CC",
    value: "VW Passat CC",
    img: "/images/vwpassat.jpg",
    id: crypto.randomUUID(),
  },
];
export const pickUp = [
  { name: "Select your pickup location" },
  { name: "Ahmedabad", id: crypto.randomUUID() },
  { name: "Vadodara", id: crypto.randomUUID() },
  { name: "Surat", id: crypto.randomUUID() },
  { name: "Banaskatha", id: crypto.randomUUID() },
  { name: "Rajkot", id: crypto.randomUUID() },
  { name: "Porbandar", id: crypto.randomUUID() },
];
export const drop = [
  { name: "Select your drop location" },
  { name: "Ahmedabad", id: crypto.randomUUID() },
  { name: "Vadodara", id: crypto.randomUUID() },
  { name: "Surat", id: crypto.randomUUID() },
  { name: "Banaskatha", id: crypto.randomUUID() },
  { name: "Rajkot", id: crypto.randomUUID() },
  { name: "Porbandar", id: crypto.randomUUID() },
];

export const car = [
  {
    name: "Audi A1 S-Line",
    img: "/images/audis1.jpg",
    id: crypto.randomUUID(),
    info: {
      rpd: 45,
      model: "Audi",
      mark: "A1",
      year: 2012,
      door: "4/5",
      ac: "Yes",
      transmission: "Manuel",
      fuel: "Gasoline",
    },
  },
  {
    name: "VW Golf 6",
    img: "/images/vw-golf.jpg",
    id: crypto.randomUUID(),
    info: {
      rpd: 37,
      model: "Golf 6",
      mark: "Volkswagen",
      year: 2008,
      door: "4/5",
      ac: "Yes",
      transmission: "Manuel",
      fuel: "Diesel",
    },
  },
  {
    name: "Toyota Camry",
    img: "/images/toyota.jpg",
    id: crypto.randomUUID(),
    info: {
      rpd: 30,
      model: "Camry",
      mark: "Toyota",
      year: 2006,
      door: "4/5",
      ac: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  },
  {
    name: "BMW 320 Modernline",
    img: "/images/bmw.jpg",
    id: crypto.randomUUID(),
    info: {
      rpd: 35,
      model: "320",
      mark: "BMW",
      year: 2012,
      door: "4/5",
      ac: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  },
  {
    name: "Mercedeces-Benz GKL",
    img: "/images/mercedes.jpg",
    id: crypto.randomUUID(),
    info: {
      rpd: 50,
      model: "Benz GLK",
      mark: "Mercedes",
      year: 2006,
      door: "4/5",
      ac: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  },
  {
    name: "VW Passat CC",
    img: "/images/vwpassat.jpg",
    id: crypto.randomUUID(),
    info: {
      rpd: 25,
      model: "Passat CC",
      mark: "Volkswagen",
      year: 2008,
      door: "4/5",
      ac: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  },
];
